backend/core/urls.py
from django.urls import path

from backend.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

backend/expense/urls.py
from django.urls import path

from backend.expense import views as v

app_name = 'expense'


urlpatterns = [
    path('', v.expense_list, name='expense_list'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

from .api import api

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('expense/', include('backend.expense.urls', namespace='expense')),
    path('api/v1/', api.urls),
    path('admin/', admin.site.urls),
]

backend/expense/models.py
from datetime import datetime

from django.db import models


class Person(models.Model):
    name = models.CharField('nome', max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    description = models.CharField('descrição', max_length=120)
    value = models.DecimalField('valor', max_digits=7, decimal_places=2)
    date_payment = models.DateField('data', null=True, blank=True)
    person = models.ForeignKey(
        Person,
        on_delete=models.SET_NULL,
        verbose_name='pessoa',
        related_name='expenses',
        null=True,
        blank=True
    )
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'despesa'
        verbose_name_plural = 'despesas'

    def __str__(self):
        return f'{self.description}'

    def date_payment_display(self):
        if self.date_payment:
            date_str = self.date_payment.isoformat()
            iso_date = datetime.fromisoformat(date_str)
            return iso_date.strftime('%d/%m/%Y')
        return ''

backend/expense/forms.py
from django import forms

from .models import Expense


class ExpenseForm(forms.ModelForm):
    date_payment = forms.DateField(
        label='Data',
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
            },
        ),
        input_formats=('%Y-%m-%d',),
    )

    class Meta:
        model = Expense
        fields = (
            'description',
            'value',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['value'].widget.attrs['min'] = 0

        for field_name, field in self.fields.items():
            field.widget.attrs['x-model'] = f'editItem.{field_name}'

backend/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'core/index.html'
    return render(request, template_name)

backend/expense/views.py
from django.shortcuts import render

from .forms import ExpenseForm


def expense_list(request):
    template_name = 'expense/expense.html'
    form = ExpenseForm()
    context = {'form': form}
    return render(request, template_name, context)

backend/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>AlpineJS • Django Ninja • Pico.css</title>
  <meta
    name="description"
    content="A classic company or blog layout with a sidebar. Built with Pico CSS."
  />
  <link rel="shortcut icon" href="https://picocss.com/favicon.ico" />
  <link rel="canonical" href="https://picocss.com/examples/company/" />

  <!-- Pico.css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css" />

  <!-- Custom styles for this example -->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" />

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Alpine.js -->
  <script src="//unpkg.com/alpinejs" defer></script>

  <!-- Axios -->
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  </head>

<body>
  <!-- Hero -->
  <div
    class="hero"
    data-theme="dark"
  >
    <nav class="container-fluid">
      <ul>
        <li>
          <a
            href="https://www.youtube.com/c/RegisdoPython/videos"
            class="contrast"
          ><strong>Regis do Python</strong></a>
        </li>
        <li>
          <a href="{% url 'expense:expense_list' %}">Despesas</a>
        </li>
      </ul>
    </nav>
    <header class="container">
      <hgroup>
        <h1>Despesas</h1>
        <h2>Exemplo de CRUD feito com AlpineJS e Django Ninja.</h2>
      </hgroup>
      <p><a
          href="https://github.com/rg3915/alpinejs-django-ninja-crud"
          target="_blank"
          role="button"
        >Github</a></p>
      <p>Imagem by Unsplash</p>
    </header>
  </div>
  <!-- ./ Hero -->

  <!-- Main -->
  <main class="container">
    {% block content %}{% endblock content %}
  </main>
  <!-- ./ Main -->

  <!-- Footer -->
  <footer class="container">
    <small>Built with <a href="https://picocss.com">Pico</a> •
      <a href="https://github.com/picocss/examples/tree/master/v1-company/">Source code</a></small>
  </footer>
  <!-- ./ Footer -->

  {% block js %}{% endblock js %}
</body>

</html>

backend/core/templates/core/index.html
{% extends "base.html" %}

{% block content %}
<div class="grid">
  <section>
    <hgroup>
      <h2>Mockup</h2>
    </hgroup>
    <p>
      Este é o exemplo do mockup desenvolvido neste projeto.
    </p>

    <a
    href="{% url 'expense:expense_list' %}"
    class="mb-2"
    role="button"
  >Clique aqui</a>

    <figure>
      <img
        src="https://raw.githubusercontent.com/rg3915/alpinejs-django-ninja-crud/main/img/mockup.png"
        alt="Mockup"
      />
    </figure>
  </section>
</div>
{% endblock content %}

backend/expense/templates/expense/expense.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div x-data="getItems">
  <hgroup>
    <h2>Despesas</h2>
    <h3>Exemplo de despesas</h3>
  </hgroup>

  <a
    href="#"
    role="button"
    @click.prevent="openModal()"
  >Adicionar</a>

  <table role="grid">
    <thead>
      <tr>
        <th scope="col">Descrição</th>
        <th
          scope="col"
          dir="rtl"
        >Valor</th>
        <th
          scope="col"
          dir="rtl"
        >Data</th>
        <th
          scope="col"
          class="text-center"
        >Ações</th>
      </tr>
    </thead>
    <tbody>
      <template
        x-for="(item, index) in items"
        :key="item.id"
      >
        <tr>
          <td
            x-text="item.description"
            x-show="!item.isEdit"
          >Almoço</td>
          <!-- Edit -->
          <td x-show="item.isEdit">
            <input
              class="mb-0"
              type="text"
              x-model="editItem.description"
            />
          </td>

          <td
            dir="rtl"
            x-text="'R$ '+item.value"
            x-show="!item.isEdit"
          >R$ 32,00</td>
          <!-- Edit -->
          <td
            dir="rtl"
            x-show="item.isEdit"
          >
            <input
              class="mb-0"
              type="number"
              min="0"
              step="0.01"
              x-model="editItem.value"
            />
          </td>

          <td
            dir="rtl"
            x-text="item.date_payment_display"
            x-show="!item.isEdit"
          >02/01/24</td>
          <!-- Edit -->
          <td
            dir="rtl"
            x-show="item.isEdit"
          >
            <input
              class="mb-0"
              type="date"
              x-model="editItem.date_payment"
            />
          </td>

          <td
            class="text-center"
            x-show="!item.isEdit"
          >
            <!-- Update -->
            <i
              class="fa fa-lg fa-pencil-square-o"
              @click="getItem(item)"
            ></i>
            <!-- Delete -->
            <i
              class="fa fa-lg fa-close ml-2 is-danger"
              @click="deleteItem(item,index)"
            ></i>
          </td>
          <!-- Edit -->
          <td
            class="text-center"
            x-show="item.isEdit"
          >
            <div>
              <!-- Confirm -->
              <a
                href=""
                role="button"
                @click.prevent="saveData()"
              >
                <i class="fa fa-check"></i>
              </a>
              <!-- Cancel -->
              <a
                href=""
                role="button"
                class="contrast"
                @click.prevent="cancelItem(item)"
              >
                <i class="fa fa-close"></i>
              </a>
            </div>
          </td>
        </tr>

      </template>
    </tbody>
    <tfoot>
      <tr>
        <td scope="col">Total</td>
        <td
          scope="col"
          dir="rtl"
          x-text="'R$ '+total()"
        >R$ 97,40</td>
        <td
          scope="col"
          dir="rtl"
        ></td>
        <td
          scope="col"
          dir="rtl"
        ></td>
      </tr>
    </tfoot>
  </table>

  <!-- Modal -->
  <!-- O open é do Pico.css, mas com dois pontos na frente ele vira um bind do AlpineJS. -->
  <dialog :open="isOpen">
    <article>
      <header>
        <a
          href=""
          aria-label="Close"
          class="close"
          @click.prevent="resetForm()"
        ></a>
        Adicionar Despesa
      </header>
      <form @submit.prevent="saveData()">
        <label for="">{{ form.description.label }}</label>
        {{ form.description }}

        <div class="grid">
          <div>
            <label for="">{{ form.value.label }}</label>
            {{ form.value }}
          </div>

          <div>
            <label for="">{{ form.date_payment.label }}</label>
            {{ form.date_payment }}
          </div>
        </div>

        <footer class="grid">
          <button
            type="button"
            class="secondary"
            @click="resetForm()"
          >Cancelar</button>
          <button type="submit">Salvar</button>
        </footer>
      </form>
    </article>
  </dialog>
</div>
{% endblock content %}

{% block js %}
<script
  src="{% static 'js/expense.js' %}"
  data-tokens='{ "csrf": "{{ csrf_token }}" }'
></script>
{% endblock js %}